export { default as CompanyLogoUrl } from "./images/company-logo.jpg";
export { default as StockEventImg1 } from "./images/stock_ev_1.png";
export { default as StockEventImg2 } from "./images/stock_ev_2.png";
export { default as StockEventImg3 } from "./images/stock_ev_3.png";
export { default as StockEventImg4 } from "./images/stock_ev_4.png";
export { default as StockEventImg5 } from "./images/stock_ev_5.png";
export { default as StockEventImg6 } from "./images/stock_ev_6.png";

export { CompanyLogo } from "./images/company-logo";

export { RightArrows } from "./icons/right-arrows";
export { EventsIcon } from "./icons/events-icon";
export { ClientIcon } from "./icons/client-icon";
export { LogoutIcon } from "./icons/logout-icon";
export { DarkModeIcon } from "./icons/dark-mode-icon";
export { LightModeIcon } from "./icons/light-mode-icon";
export { PdfIcon } from "./icons//pdf-icon";
export { ExcelIcon } from "./icons/excel-icon";
export { SearchIcon } from "./icons/search-icon";
export { LeftArrow } from "./icons/left-arrow";
export { TransactionsIcon } from "./icons/transactions-icon";
export { RefreshIcon } from "./icons/refresh-icon";
export { TickIcon } from "./icons/tick-icon";
export { DownSortArrow } from "./icons/down-sort-arrow";
export { RightPaginationIcon } from "./icons/right-pagination-icon";
export { LeftPaginationIcon } from "./icons/left-pagination-icon";
export { DblLeftPaginationIcon } from "./icons/dbl-left-pagination-icon";
export { DblRightPaginationIcon } from "./icons/dbl-right-pagination-icon";
export { EllipsisIcon } from "./icons/ellipsis-icon";
export { HistoryIcon } from "./icons/history-icon";
